### ISSUE TITLE
Any news on documentation?

### ISSUE THREAD

**Issue by val-storm** [jsdoop/jsdoop#38]
Really excited about this project. I teach a machine learning for artists class and I think this would be great to show the class and have them be able to share resources. I've downloaded your paper, but, any chance a simple quickstart will be available soon?

**Comment by jamorell** [comment]
Hi val-storm, thanks so much for your interest in our project :). I'm sorry I couldn't get back to you sooner, but I've been very busy. We are now working on refactoring all the code and testing new ideas. We didn't want to release the stable public version yet because we are working on improving the library. In any case, I'll try to provide documentation and an example with a "hello world" in a few weeks. 

Thanks again for your patience, and I hope you will continue to support us in our work.

**Comment by Aditya-Sihmar** [comment]
Hey, I read your paper and wanted to build new software on top of your library but I need documentation for that purpose. When are you planning to release the documentation and a stable version for your library?

**Comment by jamorell** [comment]
Hello Aditya,

Thank you for your interest. We are finishing a new and more stable version of the library, and we hope to publish it with the documentation in January. Please, just a little more patience.

Thank you so much!

**Comment by bitnom** [comment]
> Hello Aditya,
> 
> Thank you for your interest. We are finishing a new and more stable version of the library, and we hope to publish it with the documentation in January. Please, just a little more patience.
> 
> Thank you so much!

I have a slew of projects I've been putting off that this library could potentially jump-start. I'm about to try the code. Anything I should beware of?

**Comment by jamorell** [comment]
> > Hello Aditya,
> > Thank you for your interest. We are finishing a new and more stable version of the library, and we hope to publish it with the documentation in January. Please, just a little more patience.
> > Thank you so much!
> 
> I have a slew of projects I've been putting off that this library could potentially jump-start. I'm about to try the code. Anything I should beware of?

Hi TensorTom,

I thank you very much for your interest in the library.
You are right to be impatient. I am currently working on a new paper in which we are trying to perform asynchronous training using the library. I have been trying to finish the work before publishing the new code and documentation, but I  delayed more than I thought.

I will try to update it as soon as possible. I hope when I do, you all help me to improve it and add new features.

Thank you!

**Comment by aidanmclaughlin** [comment]
Hello jamorell, hope you are well. Very excited for the future of JSDoop. I understand writing documentation takes awhile. Is there anywhere we can find documentation on JSDoop 1.0 while we’re waiting for 2.0’s documentation? Thanks!

**Comment by jamorell** [comment]
I am very sorry for the delay. I have added an example for running JSDoop 2.0 locally. I will expand it progressively. Please let me know if you have any trouble. You are also welcome if you want to collaborate on the library.

Thank you very much for your interest in this work.
